name: Run TypeScript Compiler

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.18.2]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm
      run: npm install npm@9.8.1 -g
    - name: Install dependencies
      run: npm ci
    - name: Run typescript compiler
      run: npm run build --if-present
